### ISSUE TITLE
Point seems not increase

### ISSUE THREAD

**Issue by seeve2027** [Widiskel/initverse-tx-bot#2]
Im not sure but i see that, checkin is working properly (alr increased points) but swapping didnt increase points

**Comment by seeve2027** [comment]
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/054e5232-ddf5-44dc-86cc-b1def09d0832" />

**Comment by seeve2027** [comment]
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/12eb755f-1d41-4b6b-9db5-d14e04cddd3a" />
swapping hasnt increased point for 2 days

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Initverse SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by seeve2027** [comment]
seems okay now. i will close this
